#+TITLE: TOEFL Writing Materials
* Student - Professor - Campus
** Students+
** Professor+
paper title reputation income lecture ...
** University+
reputation, attract students of better quality; social investment
library, labs to ensure the better quality of learning and
doing researches
** Society+
Here are some examples:

*** Medical
in the medical field, currently there are still many fatal diseases
threatebubf people's lives, such as cancers and AIDS.
With more professors doing deep researches, there are larger
chances that in the future, patients suffer from these
diseases might be better treated or even get entriely cured.
*** Environment
Also, modern people are increasingly bothered by the deteriorating
natural environment. If professors devote themselves to finding
a cleaner source of energy with lower cost to replace the use of 
fossil fuels such as gasoline and coals, people surely would have
higher life quality.
*** Population
Besides, even for now, millions people still suffer from famine
in this world. Why not try to do the research and find better ways to maximize
the crop yields?

Therefore, now that prefessors function greatly in
pushing the overall progress of the society, shouldn't they
spare more time doing academic researches.

* Practice - the government needs to invest some money on beautiful things and not just on things that are beautiful
** agreed
** asthetic objects contribute to people's confidence
Olympic games. Confidence -> Creativity
** asthetic objects improve the cultural value of a nation
Spring festival. Rock music. 
** asthetic objects attracts tourists
Travelling industries could easily capitalize on these beautiful scenaries.
* Practice - advertisements targeted at children aged from 2 to 5 should be abandoned
toys, milk formula, diaper, snacks, study machine
** agreed
** advertising imbues false info
Toddler commodities require high quality
** disabling advertising generates funds for quality control
Disabling advertising, and encouraging quality greatly benefits a country's next generation.
** toddlers lack self control and could be easily prodded by adult-level advertisements, they would also mimic the dangerous behaviors appeared in advertisements
Itchy and Scratchy level-advertisement could really... well.. wreck havoc in a toddler's brain

* Practice - others' answer to the ASTHETIC question
** Improve the social stability
A blue-collar named Jason is just earning a humble amount of wage. Besides the daily expenses, hardly any money could be left
for other uses. However, recently his wife is diagnosed with lung cancers, which surlely requires large amount of money.
But the medical welfare the government provides is far from enough to cover the money needed for an operation.
So Jason is left with no choice but to rob the pedestrains. As we cab see gere, if the government had provided better medical
benefit for the citizens, this tragedy would not have happen, entailing a higher social stability.
Isn't is something that the government longs for?

* Practice - others' answer to the TODDLER ADVERTISEMENT question
** DISAGREE - ADS ALLOWED
** Company's benefits
For the company. The ads are a good way to promote the product, by which they can have better revenue and profits.
Under such condition, they can put more money to develop even more and better goods for the children.
** Parents can acknowledge the children's demands
For the parents, the existence of advertisements better helps parents find children's real needs, and
also save a lot of time that otherwise should be spent on collecting info. 

* Colleges and universities should offer students better job preparation before they start working
** Students' benefits
After job prep, students could easily beat out other unprepared candidates when entering the job market, occupying the best positions.
Teacher's version: The more job preparations universities provide, the sharper edges students will gain in job-hunting.

*** Unanswered Questions
What vacation prep? What benefit?
internship: experience, knows how to deal with problems
seminars: how to ace your interview

here are some examples: if a student does not have any working experience,
he will do things by the books. But in reality, things could be far more complicated.
For example, in order to accomplish a good sales plan, one should not only consider the 
company productivity and the market demand -- just what the book says, but also
the governmental policy and the competitors' info. The latter two, actually,
is nowhere in the books; one could only realize them through job and experience.
Also, the university needs to provide some interview-related lectures for students, through which
students might better be aware of some tricks and traps during an interview.
For example, at times interviewers might pose some really challenging questions, such as
"given your poor academic performance, why should we hire you?".
Students should realize that the interviewers are not trying to despise students, but are observing
the instant reactions of the candidates when facing huge pressures.
** Company's benefits
** University's benefits
And let's not forget the benefits the university itself could gain in this policy.
Think about it: when students find it easier to hunt for jobs, the employment
rate of the entire college would skyrocket, which surely brings about higher reputation
of the university. Accordigly, not onl students of higher quality could be attracted,
but also more social investment would flow into the university -- these
investments, in fact, could in turn be put to renew an upgrade to the libraries and labs.
Reports show that universities that have generally higher reputation could
receive up to ten million funds from the commercial groups, companies and social 
institutions. Surely, this is a benign circle that no university would ever resist;
therefore, now that this policy benefits so tremendously, why not try to offer
better job prep programs for students?

* People should insist on a challenging plan rather than a practical plan
** I am too lazy and tired, fustrated, exasperated to enforce thinking... zzzzz...
Enforce the different perspectives....... see the notes

Now the teacher's version
** Thesis: practical plan
** First Para
When we are making a plan, what are we longing for? The successful accomplishment
of a certain goal, of course. But which type of plan can better enforce us to achieve the
ultimate goal? Of course, the practical plan, because challenging ones usually
entail tensions and anxiety. Under these circumstances, people will easily
give up. Take my friend Jason for example.
Jason is a bit overweight, because of which his ex-girlfriend broke up with him.
Stimulated by this, he decided to lose 40 pounds in just 4 weeks. 
You can imagine how challenging it is -- in these 4 weeks, every day
he was determined to eat __small amount__ (maybe we should enforce better words..)
of vegetables and fruits; he should strictly control the intake of 
meat, his favorate food. He also needed to jog at least 20 miles every single day,
so there goes the treadmill.
It did not last more than five days until his killing appetite and the gruesome
exercises nearly drove him demented; he failed.
He could achieve more if he set a more mild plan; it would be far easier to reach
his goal.
** Second Para
Besides that, what challenging plan might also induce is the destroy
of people's health, both mentally and physically. I have my own experience.
In my junior year of college, I decided to apply for a postgraduate school
in the US. At that time, I was left with little time to prepare for
my TOEFL test. I had no choice but to set a very compact and challenging plan
for myself -- three hundred vocab reciting a day, fifty long sentence analyzation
and ten lectures listening a day.
In fact, other than study, barely any time could be squeezed to other
things such as hanging out with friends, watching movies, and so on. Sometimes
in order to finish the tasks of a particular day, I even ignored my
normal meals and fully devoted myself to learning. (Really... such grim conditions...?)
Sticking to this plan for nearly three months, my efforts paid off -- I scored
a 106. Yet I was diagnosed with chronic appendicitis; it could metastasis into
urgent appendicitis and endanger my life.
If ever to choose again, I would never sacrifice my health just to fulfill my
goal.

* People can take care of their family members better in big cities than in countryside

* Working 3 days a week with longer hours is better than the current conditions.
** Sample
*** The negative impact of overwork
To begin with, working 5 days a week is a sure guarantee for people's both
mental and physical health. Why is this so? As we all know, in order to
keep a normal mental state, people need to balance their daily work and rest.
For example, every day we might need some time to hang out with friends,
to have a nice meal, to watch a great movie, to enjoy some relaxing music,
and so on, so that we could alleviate the pressure from the overwhelming work
and study. 
However, the 3-day working schedule means that one has to work for even over
10 hours per day, which surely deprives people of the chance to relax and to
maintain a good mental condition. With time goes by,
people might suffer from chronic mental diseases such as insomnia, depression
and son on. Also, this working policy might threaten people's physical
health as well. Since the daily work might mouunt for so much,
sometimes people even don't hae the chance to have lunch or supper,
just in order to finish the work in that particular day. Of course,
the irregular diet might lead to physical diseases such as appendicitis.

*** The negative impact of overwork to the company
And let's not forget about the potential loss this policy might bring
to the entire company. You might be wondering: what does this have to do
with the company profit? In fact, a company can hardly thrive unless its
employees work with high efficiency and low error rate. But as we can imagine,
the longer someone works in a day, the higher possibility he might feel
exhausted, and thus lower the...

*** The loss of efficiency when overwork
The following example might even better illustrate this point. My uncle Jason is
a senior manager in a law firm. Once he had a really exhausting day: not
only did he meet up to 5 clients, but also he filed a new contract to be
signed in the following phase. Nonetheless, just because of his
over exhaustion, he mistakenly put the amount of the service fee to 10000
instead of the should-be 100000. Surely, you can imagine how this
mistake had resutled in the loss for hte entire company. Thus, a wise
company will not ask its employees to work for such long hourse every
single day.

* Students could receive better, more efficient education if they study for 11 months a year
** Education is not only in school
** What would your opponents think?
some people might argue that the longer students learn, the mroe knowledge
they could absorb. 

* To increase economic growth, the government should ignore the environmental concerns.
** Disagree
*** Ignoring x-> Economic Growth
Environment, if damaged -> no tourists -> growth waning
Environment -> damaged -> those with concern about life quality -> seek a better place

**** Sp1.
***** Environment's relationship with economy.
In fact, the worse the environment is, the worse the economic condition might be,
which is against many people's belief. Why is this so? With the poor environment,
it is les likely that tourists will take a visit to the locality, which apparently
destroys the local tourism industry, an important component of the local
economy.

[LBQ's version]
Education level affects economical growth greatly. With poor environments, those
elites who heavily concern about their living condition will eventually seek
asylum from smog, polluted air and sordid water in countries with better
environment conditions. In penance for loss elites, the country then must
alter the policies and improve the environment -- impeding economical growth in the way.
Thus, it would be far more efficient to protect the environment
during economic development instead of heedlessly enforcing economical growth
and prodding the elites to escape the country.

If the E gets worsening off, talents, especially those who demand
highly for high living quaslity, will leave this city or country, which leads to the lack of
support for the economic construction.

Unless the E is well-protected, talents will choose to

what's worse, the deteriorating environment will inevitably drive away many talents,
especially those who dcemand highly for exceptional living quality.
As a consequence, there will be a lack of support for the economic
construction of the economy.

Therefore, now that the environment has everything to do with the
economy, how could the government turn a blind eye to the environmental protection?
*** Even if it can, X, damage to health
**** Material: How environment pertains to health
And let's not forget about the disastrous effect a poor environment could
exert on our physical health. 

* A government should focus its budget more on young children education than on universities
** Sp1
The primary education shapes students' thinking mode, learning habit and value
and thus need heavy investment on great teachers and advanced 
facilities. [Reference your materials directly]

** Sp2
Some people might argue that the college education
is of even greater importance, because it is
the bridge connecting the unvicersity and the society;
so students need the best libraries and laboratory.
These, surely, needs the governmental fund.
Nonetheless, is the municipal fund the only financial support
for the universities? Surely not, because there are still plenty of social investment,
alumni donation, and so on to support the development of universities.

* WTF - Should I go to NewTouhou or OldSihou
** Diff within paragraphs
Learning in NewTouhou .. Exp. .. but, in comparison, OldSihou's teacher
only has a TOEFL 90 and they TEACH!
** Inline Diff
*** sp1 NewTouhou -- go
*** sp2 some people say that OldSihou has better equipment

