
* Student - Professor - Campus
** Students+
** Professor+
paper title reputation income lecture ...
** University+
reputation, attract students of better quality; social investment
library, labs to ensure the better quality of learning and
doing researches
** Society+
Here are some examples:

*** Medical
in the medical field, currently there are still many fatal diseases
threatebubf people's lives, such as cancers and AIDS.
With more professors doing deep researches, there are larger
chances that in the future, patients suffer from these
diseases might be better treated or even get entriely cured.
*** Environment
Also, modern people are increasingly bothered by the deteriorating
natural environment. If professors devote themselves to finding
a cleaner source of energy with lower cost to replace the use of 
fossil fuels such as gasoline and coals, people surely would have
higher life quality.
*** Population
Besides, even for now, millions people still suffer from famine
in this world. Why not try to do the research and find better ways to maximize
the crop yields?

Therefore, now that prefessors function greatly in
pushing the overall progress of the society, shouldn't they
spare more time doing academic researches.

* Should government support artists?
