#+TITLE: TOEFL Writing Materials
* Student - Professor - Campus
** Students+
** Professor+
paper title reputation income lecture ...
** University+
reputation, attract students of better quality; social investment
library, labs to ensure the better quality of learning and
doing researches
** Society+
Here are some examples:

*** Medical
in the medical field, currently there are still many fatal diseases
threatebubf people's lives, such as cancers and AIDS.
With more professors doing deep researches, there are larger
chances that in the future, patients suffer from these
diseases might be better treated or even get entriely cured.
*** Environment
Also, modern people are increasingly bothered by the deteriorating
natural environment. If professors devote themselves to finding
a cleaner source of energy with lower cost to replace the use of 
fossil fuels such as gasoline and coals, people surely would have
higher life quality.
*** Population
Besides, even for now, millions people still suffer from famine
in this world. Why not try to do the research and find better ways to maximize
the crop yields?

Therefore, now that prefessors function greatly in
pushing the overall progress of the society, shouldn't they
spare more time doing academic researches.

* Practice - the government needs to invest some money on beautiful things and not just on things that are beautiful
** agreed
** asthetic objects contribute to people's confidence
Olympic games. Confidence -> Creativity
** asthetic objects improve the cultural value of a nation
Spring festival. Rock music. 
** asthetic objects attracts tourists
Travelling industries could easily capitalize on these beautiful scenaries.
* Practice - advertisements targeted at children aged from 2 to 5 should be abandoned
toys, milk formula, diaper, snacks, study machine
** agreed
** advertising imbues false info
Toddler commodities require high quality
** disabling advertising generates funds for quality control
Disabling advertising, and encouraging quality greatly benefits a country's next generation.
** toddlers lack self control and could be easily prodded by adult-level advertisements, they would also mimic the dangerous behaviors appeared in advertisements
Itchy and Scratchy level-advertisement could really... well.. wreck havoc in a toddler's brain

* Practice - others' answer to the ASTHETIC question
** Improve the social stability
A blue-collar named Jason is just earning a humble amount of wage. Besides the daily expenses, hardly any money could be left
for other uses. However, recently his wife is diagnosed with lung cancers, which surlely requires large amount of money.
But the medical welfare the government provides is far from enough to cover the money needed for an operation.
So Jason is left with no choice but to rob the pedestrains. As we cab see gere, if the government had provided better medical
benefit for the citizens, this tragedy would not have happen, entailing a higher social stability.
Isn't is something that the government longs for?

* Practice - others' answer to the TODDLER ADVERTISEMENT question
** DISAGREE - ADS ALLOWED
** Company's benefits
For the company. The ads are a good way to promote the product, by which they can have better revenue and profits.
Under such condition, they can put more money to develop even more and better goods for the children.
** Parents can acknowledge the children's demands
For the parents, the existence of advertisements better helps parents find children's real needs, and
also save a lot of time that otherwise should be spent on collecting info. 

* Colleges and universities should offer students better job preparation before they start working
** Students' benefits
After job prep, students could easily beat out other unprepared candidates when entering the job market, occupying the best positions.
Teacher's version: The more job preparations universities provide, the sharper edges students will gain in job-hunting.

*** Unanswered Questions
What vacation prep? What benefit?
internship: experience, knows how to deal with problems
seminars: how to ace your interview

here are some examples: if a student does not have any working experience,
he will do things by the books. But in reality, things could be far more complicated.
For example, in order to accomplish a good sales plan, one should not only consider the 
company productivity and the market demand -- just what the book says, but also
the governmental policy and the competitors' info. The latter two, actually,
is nowhere in the books; one could only realize them through job and experience.
Also, the university needs to provide some interview-related lectures for students, through which
students might better be aware of some tricks and traps during an interview.
For example, at times interviewers might pose some really challenging questions, such as
"given your poor academic performance, why should we hire you?".
Students should realize that the interviewers are not trying to despise students, but are observing
the instant reactions of the candidates when facing huge pressures.
** Company's benefits
** University's benefits
And let's not forget the benefits the university itself could gain in this policy.
Think about it: when students find it easier to hunt for jobs, the employment
rate of the entire college would skyrocket, which surely brings about higher reputation
of the university. Accordigly, not onl students of higher quality could be attracted,
but also more social investment would flow into the university -- these
investments, in fact, could in turn be put to renew an upgrade to the libraries and labs.
Reports show that universities that have generally higher reputation could
receive up to ten million funds from the commercial groups, companies and social 
institutions. Surely, this is a benign circle that no university would ever resist;
therefore, now that this policy benefits so tremendously, why not try to offer
better job prep programs for students?

* People should insist on a challenging plan rather than a practical plan
** I am too lazy and tired, fustrated, exasperated to enforce thinking... zzzzz...
Enforce the different perspectives....... see the notes

Now the teacher's version
** Thesis: practical plan
** First Para
When we are making a plan, what are we longing for? The successful accomplishment
of a certain goal, of course. But which type of plan can better enforce us to achieve the
ultimate goal? Of course, the practical plan, because challenging ones usually
entail tensions and anxiety. Under these circumstances, people will easily
give up. Take my friend Jason for example.
Jason is a bit overweight, because of which his ex-girlfriend broke up with him.
Stimulated by this, he decided to lose 40 pounds in just 4 weeks. 
You can imagine how challenging it is -- in these 4 weeks, every day
he was determined to eat __small amount__ (maybe we should enforce better words..)
of vegetables and fruits; he should strictly control the intake of 
meat, his favorate food. He also needed to jog at least 20 miles every single day,
so there goes the treadmill.
It did not last more than five days until his killing appetite and the gruesome
exercises nearly drove him demented; he failed.
He could achieve more if he set a more mild plan; it would be far easier to reach
his goal.
** Second Para
Besides that, what challenging plan might also induce is the destroy
of people's health, both mentally and physically. I have my own experience.
In my junior year of college, I decided to apply for a postgraduate school
in the US. At that time, I was left with little time to prepare for
my TOEFL test. I had no choice but to set a very compact and challenging plan
for myself -- three hundred vocab reciting a day, fifty long sentence analyzation
and ten lectures listening a day.
In fact, other than study, barely any time could be squeezed to other
things such as hanging out with friends, watching movies, and so on. Sometimes
in order to finish the tasks of a particular day, I even ignored my
normal meals and fully devoted myself to learning. (Really... such grim conditions...?)
Sticking to this plan for nearly three months, my efforts paid off -- I scored
a 106. Yet I was diagnosed with chronic appendicitis; it could metastasis into
urgent appendicitis and endanger my life.
If ever to choose again, I would never sacrifice my health just to fulfill my
goal.

* People can take care of their family members better in big cities than in countryside

* Working 3 days a week with longer hours is better than the current conditions.
