#+TITLE: TOEFL Writing Notes
* Synopsis
** The Yello Textbook
the main textbook;
** The White Textbook
contains language rhetorical usage.
On the class we discuss the thinking process.
This book discribes the rudimentary usage of rhetorics in the test.
** Motto
Practice makes perfect.
Will practice a lot.
** Lessons
total count: 4
* Lesson 1
** Ice-breaking - What is the government's role? Helath : Economy
*** The thinking process
how to enrich the paragraph? how to manifest my subpoints
*** The language process
**** correctness
common verbs - advocate
translational errors emitted by coercing Chinese to English
**** continuity - how the language flows
As the society is developing rapidly, People neither have time to entertain themselves nor are left with time to be concerned with others.
-- my version
The rapid social development leads to less personal entertainment time and less time to concern others.
**** focibility
example:
learning in nos helps to boost my efficiency
my academic performance could not see the dramatic rise unless I learn here at NOS without taking courses here. ;;complete nonsense
**** materials
the bottleneck 
*** example: how people botch their thinking in the test
University student should take the test or not.

'''
University students are older enough to make their own
  choose than primary students are.

Because, in nowadays, technologies are explored, there
is so much knowledge in each field that even putting all 
their efforts on it, they could not master all the
 knowledge. Forcing university students taking
 history courses could be a waste of time.

Also, university should choose the courses according
to their interests. Only in this way, could they be 
effective in every day's study. Therefore. the university
 should not just regulate students taking the
 history courses but give them the freedom of choosing
 courses.
'''

** Individual Writing - Writing Structure
*** Intro(30-80 words)
*** Body Paragraph(Fully Developmed)(100-150words)
*** Body Paragraph(Fully Developed)(100-150words)
*** Body Para4(Conditional)
*** Conclusion(20 words)
** Intro Template
*** Example: It's necessary for family members to have regular meals with each other
When it comes to the issue whether (restate the problem) regular meals together with family members are quite essential,
surely different people hold different views based on their divergent experiences, backgrounds and values.
As for me, to have meals frequently with my parents and siblings is a MUST.
** Conclusion Template
Therefore, my idea is quite clear: even if I have to sacrifice some working and entertaining time, 
I will try my best to ensure the frequency of dinining together with family members.

* Type1 Question: To do or not to do
** What is the benefit of A
The professor should majorly educate students in college, rather than do researches.
Students + 
*** might gain deeper and more thorough understanding to the specific field when the professor is giving lectures.
Eg. When I was in my freshman year, the subprime crisis broke out, which confused me quite a lot. How did it take place? 
What's the subsequent effects to the society? Thus, I went to a lot of professors' courses, searched all sorts of books and journals. Disappointedly, however,
I was still left unclear of this issue.
This situation did not change until I went to the course of professor Jason, who was a senior researcher in the Chinese Economic Developing Center.
It was after his course that I completely understood the correlation between the housing price,
 people's expectations, the financial bubble and the subsequent financial crisis.
Therefore, isn't it the best example that indicates the necessity for professors to engage in researches?
*** Summary
1. When fabricating personal experiences, do FORESHADOW - NARRATE - RESULT
2. Collect materials (Very Important!). Materials proves to be very versatile.

** What if you can only think of only ONE example
Think of the different DIMENSIONS!
*** The thinking Flow Chart
Is it beneficial to:
study/work
friendship/entertainment
improve personality
economical benifits
convenience/health/safety


* What to do if you only have 1 argument
** Fake an opponent
*** Structure
**** Your opponent's sentiment + reason + [why]
**** How to state your reasons 
***** YOU ARE WRONG!!!!!
example: homeworking vs [my choice: officeworking]

Some people might arugue that working at home is more advisable,
because they might be more confortable when staying at home.
Nonetheless, is this really the true? Not for me, at least./
However, for me, this is not even close to the truth.

[now depict a sad you]
I am an oridinary white collar in Beijing, earning just 5000 yuan
each month. As you might know, the renting price in Beijing is 
exorbitant -- so in order to make ends meet, I have no choice but to
rent a room no larger than 10 square meters. Other than my bed, barely
anyhing else could be placed into this room -- it is quite a luxury
for me to place a desk for working or a bookcase for all my
working files.
Can you imagine anyone working confortably under such conditions?
Therefore, "cozy" might be the last choice for me to describe
the working at home. And as I know, millions of working classes
are suffering from similar situations as I am. Apparently,
it is not right to put "working at home" as "comfortable".
***** IT IS NOT IMPORTANT!!!!!
[you are right... but not significant]\

example: would you like to spend money on short-term pleasure
such as vacations, or would you like to spend money on
long-lasting things such as the jewelry?

Some people might argue that buying the jewelry is
wiser, because it might help to even earn money -- with time,
it could appreciate.

However, is the humble financial gaining really that much 
important? Not for me at least.

Let's suppose that now you have 20000 yuan in hand,
and you buy a piece of gold necklace accordingly.
After 5 years, how much could you sell it for?
Based on the current appreciation rate, 25000 might be the maximum.
This means that in these five years, the necklace makes you five thousand
yuan. But think about it: what can you do with the money in the year 2020
in Beijing? Rent a small apartment for half a month? Treat a couple of 
your friends with a nice meal? Or buy several pieces of clothes?
As we can see here, with the inlfation rate, what you can do with the extra
money is rather limited. However, if, in the first place, you have spared
the money on a trip, you possibly would have already met
someone that has changed your life, or you would have gained some
meaningful experiences that shaped your value.

example: The government should spend more money building playgrounds rather than museums.

***** LET ME GET YOU A BETTER METHOD
****** Sp1
It is undeniable that asking children to take care of their
own money effectively promotes their financial awareness and 
improves the finance-managing skills.

Connect money with commodity

finance-managing skills.
****** Sp2
Some people might argue that even if this measure eventually
works to evoke children;s financial responsibility, in the process,
there might be some potential risks that might negatively influence
children's academic performance or even mental health.
Nonetheless, don't we have any solutions to the problem?
Definitely we do. / Don't we have any alternative to achieve the same goal? 
In fact, parents should take active
roles to regulate and supervise how children spend the money;
if there is anything that goes wrong, parents need to take measures
to eliminate the negative influences. Take my own experience for 
example. In my middle school years, my mother first stated to ask me to
manage money. Each month, she would give me 1000 yuan at my own disposal.
In the first time when I had such a big amount of money in my hands, I was
overexcited, thinking I could do whatever I liked. I thus skipped my class
and stayed in a computer bar for an entire day to play DOTA. When my
mom figured this out, she strictly alerted me, sayig that if this
ever heappened again, I would never have the chance to taste
my favorite dish -- kongpao chicken from her again.
At the same time, she added that if I could keep a good record
from then on, then each month I could get extra bonus! Stimulated
by these two policies, I never went out of the track again and started to seriously 
emanage my money. Of course, that paid off. Therefore, as long as
parents and children make joint efforts, those potential risks
can be effectively wiped out.

* Good or Bad?
** Steps
What is the main problem?

Dimensions?

What would my opponents do?

** Expanding
Topic sentence + reasoning + exampling(add details) + conclusion

Your opponent's sentiments + reasoning + YOU ARE WRONG!

** Materails aka Examples

* Event type
Agree? Disagree? The way a person is dressed in is a good indication
of his/her personality
** Can I break it apart?
[They way a person is dressed] is a good [indication]
of his/her [personality]

I agree.

** Sp1 The style one prefers tells everything about him.
Here are some examples: we must have some friends around
us who always like to clad in bizarre clothes. Think about
Lady Gaga, She once even just covered herself with a piece
of beef and then attended a ball!
These people, in my opinion, are usually bold, brave, and
they are never afriad of others' judgements.
Also there are a certain group ofpeople, who strictly
follow the fashion trend: sometimes they wear lace
all over, sometimes jeans, and sometimes they dress up
with colorful stockings. Their styles keep changing;
but unfortunately, they are ofentimes weak-minded, and they
are easily influenced by others' ideas.
And let's not forget about such type of people, who 
feel unsecured unless they are in top-tier brands
such as Dior, Chanel or Burberry. Sure, they
have high demand in life quality; but at the same time,
they might be internally unconfident, so that they have to
arm themselves with luxury brands to look stronger and
more powerful.

** Sp2 Besides, one's preference of colors also reveals some pf his characteristics.

* The rules that the society expects young people to follow are too strict.
* The society is developing very quickly, and grandparents' suggestions are of no use to us now.

* Technology has made our lives simpler, rather than more complicated.
** Working and studying
** Entertaining and leisure life

* How to deal with Effect
** Can I break it down?
** What are the underlying reasons?

** Sp1.
To begin with, driven by the maximized profit,
advertisement producers tend to exaggerate the real
function of the product, or even add complete fake information
in the ads to appeal customers.
** Sp2.
However, are customers the pure victim under
such phenomenon? Not exactly. In fact, just because
customers themselves tend to attach their own 
fantasies to the product when seeing the advertisement,
the product in their minds might be much better than in reality.

* Review for the previous lesson
** Good ? Bad ?
1. Learn the main idea, the dimensions

   1. study, entertainment, moral, health, economical

2. What will your opponents do?

   1. correctness, significance, an expedient (better version of what
your opponents say)

* Effect
Is it, or is it not?
** Break it up, then exemplify (focus on the nouns of the original sentence)
rules, etc
** Cause and effect (it is... and because ..  [just list the reasons])

** How to think
1. Technology (info, communication, traffic, ...)

2. Economic (income, agriculture, industrialization)

3. Culture (openness, equalness)

4. Morality (openess, creativity)
